api/urls.py
from django.urls import include, path
from . import views 


urlpatterns = [
    path('blog/add-new-post/', views.AddPostView.as_view()),
]

banglaidj/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views as token_view

from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api/', include('api.urls')),
    path('api-token-auth/', token_view.obtain_auth_token),
    path('dashboard/', include('dashboard.urls')),
    path('', views.home, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import include, path
from .views import *


urlpatterns = [
    path('add-post', add_new_post, name='add-post'),
    path('post_detail/<int:pk>', post_detail, name='post_detail'),
    path('posts_of_category/<int:pk>', posts_of_category, name='posts_of category'),
    path('total_author/', total_author, name='total_author'),
    path('posts_of_author/<int:pk>', posts_of_author, name='posts_of_author'),
]

dashboard/urls.py
from django.urls import include, path
from .views import *

app_name = 'dashboard'

urlpatterns = [
    path('', dashboard, name='home'),
    path('post/list', authors_post_list, name='post-list'),
]

api/models.py
from django.db import models

# Create your models here.

author/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from sorl.thumbnail import ImageField
from ckeditor_uploader.fields import RichTextUploadingField



class Tag(models.Model):
	name = models.CharField(max_length=150)

	def __str__(self):
		return self.name


class Category(models.Model):
	name = models.CharField(max_length=50)

	def __str__(self):
		return self.name

	
class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	author_img = models.ImageField(upload_to='author_images', null=True, blank=True)
	author_name = models.CharField(max_length=50)
	author_description = models.TextField()
	author_facebook	= models.URLField(null=True, blank=True)
	author_twitter = models.URLField(null=True, blank=True)
	author_linkedin = models.URLField(null=True, blank=True)
	
	def __str__(self):
		return self.author_name

class PostManager(models.Manager):
	def latest_post(self):
		l_post = Post.objects.filter(is_draft=False).order_by('-date')[:4]
		return l_post
		
	def authors_post(self, author):
		return self.filter(author=author).order_by('-date')


class Post(models.Model):
	title = models.CharField(max_length=100)
	date = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
	description = RichTextUploadingField()
	category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='post')
	#tags = models.ManyToManyField(Tag)
	is_draft = models.BooleanField(default=False)

	objects = PostManager()
	
	def __str__(self):
		return self.title

dashboard/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms 
from blog.models import Post


class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post 
        # fields = '__all__'
        exclude = ('author',)
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'})
        }

api/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import AddPostSerializer


class AddPostView(APIView):
    def post(self, request):
        print("main data",request.data)
        serializer = AddPostSerializer(data=request.data)
        if serializer.is_valid():
            print(serializer.validated_data)
            serializer.save(author=request.user)
            return Response({'status': True}, status=status.HTTP_201_CREATED)
        print(serializer.errors)
        return Response({'status': serializer.errors}, status=status.HTTP_400_BAD_REQUEST)

author/views.py
from django.shortcuts import render

# Create your views here.

banglaidj/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404

from blog.models import Category, Post


# home_page_view
def home(request):
	Categorys = Category.objects.all()
	latest_post = Post.objects.latest_post()
	ctx = {'categories': Categorys, 'latest_post': latest_post}
	return render(request, 'blog/home.html', ctx)

blog/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from rest_framework.authtoken.models import Token


from .models import Category, Post, Profile
from .forms import AddPostForm


def add_new_post(request):
	categories = Category.objects.all()
	token, created = Token.objects.get_or_create(user=request.user)
	context = {'categories': categories, 'token': str(token.key)}
	return render(request, 'blog/add-new-post.html', context)


# post_detail_page_view
def post_detail(request, pk):
	post = get_object_or_404(Post, pk=pk)
	first = Post.objects.filter(is_draft=False).first()
	last = Post.objects.filter(is_draft=False).last()
	ctx = {'post': post, 'first': first, 'last': last}
	return render(request, 'blog/post_detail.html', ctx)


# posts_of_Category_page_view
def posts_of_category(request, pk):
	category_obj = get_object_or_404(Category, pk=pk)
	post = Post.objects.filter(category=category_obj, is_draft=False)
	ctx = {'category': category_obj, 'post': post}
	return render(request, 'blog/posts_of_category.html', ctx)


# total_author_page_view
def total_author(request):
	authors = User.objects.all()
	return render(request, 'blog/total_author.html', {'authors': authors})


# posts_of_author_page_view
def posts_of_author(request, pk):
	author = get_object_or_404(User, pk=pk)
	post = Post.objects.filter(author=author, is_draft=False)
	ctx = {'author': author, 'post': post}
	return render(request, 'blog/posts_of_author.html', ctx)	

dashboard/views.py
from django.shortcuts import render
from blog.models import Post 


def dashboard(request):
    return render(request, 'dashboard/dashboard.html')

def authors_post_list(request):
    posts = Post.objects.authors_post(author=request.user)
    context = {'posts': posts}
    return render(request, 'dashboard/authors_post_list.html', context)

templates/base/asidebar.html
{% load static %}
<aside class="aside-menu">
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#timeline" role="tab"><i class="icon-list"></i></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#settings" role="tab"><i class="icon-settings"></i></a>
        </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div class="tab-pane active" id="timeline" role="tabpanel">
            <div class="callout m-0 py-2 text-muted text-center bg-light text-uppercase">
                <small><b>Today</b></small>
            </div>
            <hr class="transparent mx-3 my-0">
            <div class="callout callout-warning m-0 py-3">
                <div class="avatar float-right">
                    <img src="{% static 'src/img/avatars/7.jpg' %}" class="img-avatar" alt="admin@bootstrapmaster.com">
                </div>
                <div>Meeting with
                    <strong>Lucas</strong>
                </div>
                <small class="text-muted mr-3"><i class="icon-calendar"></i>&nbsp; 1 - 3pm</small>
                <small class="text-muted"><i class="icon-location-pin"></i>&nbsp; Palo Alto, CA</small>
            </div>
            <hr class="mx-3 my-0">
            <div class="callout callout-info m-0 py-3">
                <div class="avatar float-right">
                    <img src="{% static 'src/img/avatars/4.jpg' %}" class="img-avatar" alt="admin@bootstrapmaster.com">
                </div>
                <div>Skype with
                    <strong>Megan</strong>
                </div>
                <small class="text-muted mr-3"><i class="icon-calendar"></i>&nbsp; 4 - 5pm</small>
                <small class="text-muted"><i class="icon-social-skype"></i>&nbsp; On-line</small>
            </div>
        </div>
        <div class="tab-pane p-3" id="settings" role="tabpanel">
            <h6>Settings</h6>
            <hr>
            <h6>System Utilization</h6>

            <div class="text-uppercase mb-1 mt-4">
                <small><b>CPU Usage</b></small>
            </div>
            <div class="progress progress-xs">
                <div class="progress-bar bg-info" role="progressbar" style="width: 25%" aria-valuenow="25"
                     aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <small class="text-muted">348 Processes. 1/4 Cores.</small>

            <div class="text-uppercase mb-1 mt-2">
                <small><b>Memory Usage</b></small>
            </div>
            <div class="progress progress-xs">
                <div class="progress-bar bg-warning" role="progressbar" style="width: 70%" aria-valuenow="70"
                     aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <small class="text-muted">11444GB/16384MB</small>

            <div class="text-uppercase mb-1 mt-2">
                <small><b>SSD 1 Usage</b></small>
            </div>
            <div class="progress progress-xs">
                <div class="progress-bar bg-danger" role="progressbar" style="width: 95%" aria-valuenow="95"
                     aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <small class="text-muted">243GB/256GB</small>

            <div class="text-uppercase mb-1 mt-2">
                <small><b>SSD 2 Usage</b></small>
            </div>
            <div class="progress progress-xs">
                <div class="progress-bar bg-success" role="progressbar" style="width: 10%" aria-valuenow="10"
                     aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <small class="text-muted">25GB/256GB</small>
        </div>
    </div>
</aside>

templates/base/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    {% block extrajs %}

    {% endblock %}

</head>

<!--Headers-->
{% include 'base/header.html' %}

<!-- BODY options, add following classes to body to change options

// Header options
1. '.header-fixed'					- Fixed Header

// Brand options
1. '.brand-minimized'       - Minimized brand (Only symbol)

// Sidebar options
1. '.sidebar-fixed'					- Fixed Sidebar
2. '.sidebar-hidden'				- Hidden Sidebar
3. '.sidebar-off-canvas'		- Off Canvas Sidebar
4. '.sidebar-minimized'			- Minimized Sidebar (Only icons)
5. '.sidebar-compact'			  - Compact Sidebar

// Aside options
1. '.aside-menu-fixed'			- Fixed Aside Menu
2. '.aside-menu-hidden'			- Hidden Aside Menu
3. '.aside-menu-off-canvas'	- Off Canvas Aside Menu

// Breadcrumb options
1. '.breadcrumb-fixed'			- Fixed Breadcrumb

// Footer options
1. '.footer-fixed'					- Fixed footer

-->

<body class="app header-fixed sidebar-fixed aside-menu-fixed aside-menu-hidden"  style="background-color:darkslategray">
<!--Navbar-->
{% include 'base/navbar.html' %}

<div class="app-body">
    <!--Sidebar-->
    {% include 'base/sidebar.html' %}

    <!-- Main content -->
    <main class="main">

        <!-- Breadcrumb -->
        {% include 'base/breadcrumb.html' %}

        <!-- Page contents -->
        <div class="container-fluid">
            <div class="animated fadeIn">
                {% block content %}
                {% endblock %}
            </div>

        </div>
        <!-- /.conainer-fluid -->
    </main>


    <!--Aside bar-->
    {% include 'base/asidebar.html' %}

</div>

<!--Footer-->
{% include 'base/footer.html' %}

<!--JS-->
{% include 'base/js.html' %}

</body>
</html>

templates/base/breadcrumb.html
{% load static %}
<ol class="breadcrumb">
    <li class="breadcrumb-item">Home</li>
    <li class="breadcrumb-item"><a href="#">Admin</a></li>
    <li class="breadcrumb-item active">Dashboard</li>

    <!-- Breadcrumb Menu-->
    <li class="breadcrumb-menu d-md-down-none">
        <div class="btn-group" role="group" aria-label="Button group">
            <a class="btn" href="#"><i class="icon-speech"></i></a>
            <a class="btn" href="{% url 'home' %}"><i class="icon-graph"></i> &nbsp;Dashboard</a>
            <a class="btn" href="#"><i class="icon-settings"></i> &nbsp;Settings</a>
        </div>
    </li>

    {% block breadcrumb %}
    {% endblock %}
</ol>

templates/base/footer.html
<footer class="app-footer">
    <span><a href="#">Circle Fintech</a> © 2018</span>
    <span class="ml-auto">Powered by <a href="#">Circle Fintech</a></span>
    {% block extrafooter %}
    {% endblock %}
</footer>

templates/base/header.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="CoreUI - Open Source Bootstrap Admin Template">
    <meta name="author" content="Circle Fintech">
    <meta name="keyword" content="">
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">
    <title>Circle Fintech</title>

    <!-- Icons -->
    <link href="{% static 'dist/vendors/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'dist/vendors/css/simple-line-icons.min.css' %}" rel="stylesheet">

    <!-- Main styles for this application -->
    <link href="{% static 'dist/css/style.css' %}" rel="stylesheet">

    

    {% block extrahead %}
    {% endblock %}
</head>

templates/base/js.html
{% load static %}

<!-- Bootstrap and necessary plugins -->
<script src="{% static 'dist/vendors/js/jquery.min.js' %}"></script>
<script src="{% static 'dist/vendors/js/popper.min.js' %}"></script>
<script src="{% static 'dist/vendors/js/bootstrap.min.js' %}"></script>
<script src="{% static 'dist/vendors/js/pace.min.js' %}"></script>


<!-- Plugins and scripts required by all views -->
<!--Chart JS is commented out due to console errors-->
<!--<script dist="{% static 'dist/vendors/js/Chart.min.js' %}"></script>-->

<!-- CoreUI main scripts -->

<script src="{% static 'dist/js/app.js' %}"></script>

<!-- Plugins and scripts required by this views -->

<!-- Custom scripts required by this view -->
<script src="{% static 'dist/js/views/main.js' %}"></script>

{% block script %}

{% endblock %}

templates/base/navbar.html
{% load static %}
<header class="app-header navbar">
    <button class="navbar-toggler mobile-sidebar-toggler d-lg-none mr-auto" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>

    <ul class="nav navbar-nav d-md-down-none">
        <li class="nav-item px-3">
            <a class="nav-link" href="#">Settings</a>
        </li>
    </ul>
    <ul class="nav navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle nav-link" data-toggle="dropdown" href="#" role="button"
               aria-haspopup="true" aria-expanded="false">
                <img src="{% static 'src/img/avatars/6.jpg' %}" class="img-avatar" alt="admin@bootstrapmaster.com">
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <div class="dropdown-header text-center">
                    <strong>Account</strong>
                </div>
                <a class="dropdown-item" href="#"><i class="fa fa-bell-o"></i> Updates<span
                        class="badge badge-info">42</span></a>
                <div class="dropdown-header text-center">
                    <strong>Settings</strong>
                </div>
                <a class="dropdown-item" href="#"><i class="fa fa-user"></i> Profile</a>
                <a class="dropdown-item" href="#"><i class="fa fa-wrench"></i> Settings</a>
                <a class="dropdown-item" href="#"><i class="fa fa-usd"></i> Payments<span class="badge badge-secondary">42</span></a>
                <a class="dropdown-item" href="#"><i class="fa fa-lock"></i> Logout</a>
            </div>
        </li>
    </ul>
    <button class="navbar-toggler aside-menu-toggler" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>

    {% block navbar %}
    {% endblock %}

</header>

templates/base/sidebar.html
{% load static %}
<div class="sidebar">
    <nav class="sidebar-nav">
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dashboard:home' %}"><i class="icon-speedometer"></i> Dashboard</a>
                <a class="nav-link" href="{% url 'add-post' %}"><i class="icon-speedometer"></i> Add New Post</a>
                <a class="nav-link" href="{% url 'dashboard:post-list' %}"><i class="icon-speedometer"></i> Post List</a>
            </li>
        </ul>
    </nav>
    <button class="sidebar-minimizer brand-minimizer" type="button"></button>


    {% block sidebar %}
    {% endblock %}
</div>

templates/blog/add-new-post.html
{% extends 'base/base.html' %}

{% block extrajs %}
<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

<!-- Initialize Quill editor -->
<script>
    $(document).ready(function(){
        var quill = new Quill('#textarea-input', {
        modules: {
            toolbar: [
            ['bold', 'italic'],
            ['link', 'blockquote', 'code-block', 'image'],
            [{ list: 'ordered' }, { list: 'bullet' }]
            ]
        },
        placeholder: '',
        scrollingContainer: '#scrolling-container',
        theme: 'snow'
        });
        // post 
        const url = 'http://localhost:8000/api/blog/add-new-post/'
        
        $('#submit').click(function(){
            var d = quill.getText();
            var c = $('input[type=checkbox]').prop('checked');
            console.log(c)
            post_data = {
                "title": $("#title").val(),
                "description":quill.getText(),
                "category": $('#id_category').val(),
                "is_draft": c,
            }
            console.log(post_data);
            $.ajax({
                    url: url,
                    headers: {
                        'Authorization': 'Token {{ token }}' ,
                    },
                    method: 'post',
                    data: JSON.stringify(post_data),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function(data){
                        console.log("success");
                    },
                    failure: function(errMsg) {
                         alert("error"+errMsg);
                    }
                });
        })
    });
  
</script>

{% endblock %}

{% block content %}

<div class="row">
   <div class="col-md-9">
        <div class="card h-100">
            <div class="card-header">
                <strong>Basic Form</strong> Elements
            </div>
            <div class="card-body">
                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    <div class="form-group row">
                        <div class="col-md-12">
                            <input class="form-control" id="title" type="text" name="text-input" placeholder="Text">
                            <span class="help-block">This is a help text</span>
                        </div>
                    </div>
                    
                    <div class="form-group row">  
                        <div class="col-md-12">
                            <div class="overflow-hidden" id="textarea-input" ></div>
                        </div>
                    </div>
                
                </form>
            </div>
        </div> <!--card end-->   
    </div>
    <!--right side column-->
    <div class="col-md-3">
        <div class="card">
            <div class="card-header">
                <strong>Horizontal</strong> Form
            </div>
            <div class="card-body">
                <form class="form-horizontal" action="" method="post">
                    <div class="form-group row">
                        <div class="col-md-12">
                            <select class="form-control" id="id_category" name="select1">
                                <option value="">ক্যাটাগরী</option>
                            {% for category in categories %}
                                <option value="{{ category.id }}">{{ category.name }}</option>
                            {% endfor %}
                            </select>
                        </div>
                    </div>
                        
                    <div class="form-group row">
                        <div class="col-md-12 col-form-label">
                            <div class="form-check form-check-inline mr-1">
                                <input class="form-check-input" id="id_is_draft" type="checkbox" value="check1">
                                <label class="form-check-label" for="inline-checkbox1">সংরক্ষিত রাখুন</label>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="card-footer">
                <button id="submit" class="btn btn-sm btn-primary" type="submit">
                    <i class="fa fa-dot-circle-o"></i> Submit</button>
                <button class="btn btn-sm btn-danger" type="reset">
                    <i class="fa fa-ban"></i> Reset</button>
            </div>
        </div> <!--card2 end -->
    </div> <!--/col-3 -->
</div>



{% endblock %}

templates/blog/home.html
{% extends 'main-base.html' %}

{% block content %}
<!--===================End header_section==================-->

<!--===================Start latest_post_section===========-->
    <section class="latest-posts">
      <div class="container">
        <div class="post-header">
          <h4>Latest post</h4>
          <p>{{ latest_post.count }} Items</p>
        </div>
        <div class="posts">
          {% for post in latest_post %}
          <div class="post">
            <div class="post-box">
              <h4 class="category"></h4>
              <h1><a href="{% url 'post_detail' post.pk %}">{{ post.title }}</a></h1>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </section>
<!--===================End latest_post_section=============-->

    <section class="django-course">
      <div class="container">
        <img src="/static/img/course.png" alt="">
      </div>
    </section>

<!--===================Start tutorial_series_section=======--> 
    <section class="series-section">
      <div class="container">
        <h1 class="series-title">Tutorial series</h1>
        {% for category in categories %}
        <div class="series-example">
          <div class="post-header">
            <h4>{{ category.name }}</h4>
          </div>
          <div class="posts">
            {% for post in category.post.all|slice:":4" %}
            <div class="post">
              <div class="post-box">
                <h4 class="category"></h4>
                <h1><a href="{% url 'post_detail' post.pk %}"> {{ post.title }}</a></h1>
              </div>
            </div>
            {% endfor %}
          </div>
          <div class="btn-wrap">
            <a href="{% url 'posts_of category' category.pk %}" class="check-all">See totall post of this category</a>
          </div>
        </div>
        {% endfor %}          
      </div>
    </section>
<!--===================End tutorial_series_section=========-->

<!--===================Start footer_section================-->
    {% endblock %}

templates/blog/post_detail.html
{% extends 'main-base.html' %}

{% block content %}
{% load thumbnail %}
<!--===================Start post_detail_section=========-->     
    <section class="s-post-header">
      <div class="post-header">
        <div class="post-container">
          <h1 class="post-title">
            {{ post.title }}
          </h1>
          <div class="post-info">
            <div class="author">
              {% thumbnail post.author.profile.author_img "50x50" crop="center" as im %}
              <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
              {% endthumbnail %}
              <p class="name"><a href="{% url 'posts_of_author' post.author.pk %}">{{ post.author.profile.author_name }}</a></p>
            </div>
            <div class="date">{{ post.date }}</div>
          </div>
        </div>
      </div>
    </section>

    <section class="post-content">
      <div class="container">
        <p>{{ post.description|safe }}</p>
      </div>
    </section>  
<!--===================End post_detail_section=============-->

<div class="btns-wrap">
  {% if post.pk > first.pk %}
  <a href="{% url 'post_detail' post.pk|add:'-1' %}">&laquo;  Previous Post:</a>
  {% endif %}
  {% if post.pk < last.pk %}
  <a href="{% url 'post_detail' post.pk|add:'1' %}">Next Post:  &raquo;</a>
  {% endif %}
</div>

<!--===================Start DISQUS_comment_section========-->
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://banglai-django.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript><br>
<!--===================End DISQUS_comment_section==========-->

<!--===================Start footer_section================-->
{% endblock %}

templates/dashboard/authors_post_list.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <i class="fa fa-align-justify"></i> Simple Table
        </div>
        <div class="card-body">
            <table class="table table-responsive-sm">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Date registered</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                {% for post in posts %}
                    <tr>
                        <td>{{ post.title }}</td>
                        <td>{{ post.date }}</td>
                        <td>
                        {% if post.is_draft %}
                            <span class="badge badge-danger">Draft</span>
                        {% else %}
                            <span class="badge badge-success">Published</span>
                        {% endif %}
                        </td>
                        <td>
                            <a class="btn btn-primary" href="#">Edit</a>
                            <a class="btn btn-danger" href="#">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/dashboard/dashboard.html
{% extends 'base/base.html' %}

{% block content %}

{% endblock %}